image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: true
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Main
    init: |
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      source $HOME/.poetry/env
      poetry config virtualenvs.in-project true
      poetry install
      
    command: |
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> ~/.bashrc
      source $HOME/.poetry/env
      poetry config virtualenvs.in-project true
      poetry shell
      python manage.py runserver

  # - name: Redis
  #   init: gp sync-done redis
  #   command: redis-server

ports:
  - name: Django
    description: The main application web server
    port: 8000
    # onOpen: open-browser

  # - name: Postgres
  #   port: 5432
  #   onOpen: ignore

  # - name: Web App
  #   description: The main application web server
  #   port: 8080
  #   onOpen: open-browser
# tasks:
#   - init: |
#       pyenv install 3.10.4
#       curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
#       source $HOME/.poetry/env
#       poetry install
#     command: |
#       python manage.py runserver
