# Generated by Django 4.0.5 on 2022-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0002_auto_20220615_1456"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=255)),
                ("balance", models.CharField(max_length=255)),
                (
                    "expiration_date",
                    models.IntegerField(
                        blank=True, db_column="expirationDate", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(db_column="createdAt")),
                ("updated_at", models.DateTimeField(db_column="updatedAt")),
            ],
            options={
                "db_table": "indexer_item_balances",
                "managed": False,
            },
        ),
    ]
