# Generated by Django 4.0.5 on 2022-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemShop',
            fields=[
                ('nft_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('rental_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
