# Generated by Django 4.0.5 on 2022-09-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBalance',
        ),
    ]
