# Generated by Django 4.0.5 on 2022-09-19 15:54

from django.db import migrations, models
import django.db.models.deletion
import stages.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_remove_player_stage_current'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='level_required',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_no', models.IntegerField()),
                ('reward', models.JSONField(default=stages.models.default_reward_dict)),
                ('enemy', models.JSONField(default=stages.models.default_enemy_dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_stage', to='stages.stage')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_data', models.JSONField(default=stages.models.default_play_data_dict)),
                ('start_hp', models.JSONField(default=stages.models.default_hp_dict)),
                ('result_hp', models.JSONField(default=stages.models.default_hp_dict)),
                ('skill_cool_down', models.JSONField(default=stages.models.default_skill_cool_down_dict)),
                ('is_win', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.phase')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('stage', 'phase_no'), name='unique_stage_phase_no'),
        ),
    ]
