# Generated by Django 4.0.5 on 2022-09-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_remove_player_game_play'),
        ('stages', '0002_stage_level_required_phase_gameplay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(default=None, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameplay',
            name='player',
        ),
        migrations.AddField(
            model_name='gameplaystage',
            name='current_game_play',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stages.gameplay'),
        ),
        migrations.AddField(
            model_name='gameplaystage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_play_stage_player', to='players.player'),
        ),
        migrations.AddField(
            model_name='gameplaystage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_play_stage', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='gameplay',
            name='game_play_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game_play_game_play_stage', to='stages.gameplaystage'),
        ),
        migrations.AddConstraint(
            model_name='gameplay',
            constraint=models.UniqueConstraint(fields=('game_play_stage', 'phase'),
                                               name='unique_game_play_stage_phase'),
        ),
    ]
