# Generated by Django 4.0.5 on 2022-09-21 10:57

from django.db import migrations, models
import django.db.models.deletion
import stages.models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_gameplaystage_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='level_required',
        ),
        migrations.AddField(
            model_name='gameplaystage',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='boost_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='monsters',
            field=models.JSONField(default=stages.models.default_monsters_dict),
        ),
        migrations.AddField(
            model_name='stage',
            name='require_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stage_require_stage', to='stages.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stamina_cost',
            field=models.IntegerField(default=0),
        ),
    ]
