# Generated by Django 4.0.5 on 2022-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_remove_stage_level_required_gameplaystage_is_boosted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='reward',
            field=models.JSONField(default=None, null=True),
        ),
    ]
