# Generated by Django 3.2.13 on 2022-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herouser',
            name='nft_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
