# Generated by Django 3.2.13 on 2022-06-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_alter_herouser_nft_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herouser',
            old_name='agility',
            new_name='base_agi',
        ),
        migrations.RenameField(
            model_name='herouser',
            old_name='intelligent',
            new_name='base_int',
        ),
        migrations.RenameField(
            model_name='herouser',
            old_name='strength',
            new_name='base_str',
        ),
        migrations.RenameField(
            model_name='herouser',
            old_name='vitality',
            new_name='base_vit',
        ),
    ]
