# Generated by Django 3.2.13 on 2022-06-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_auto_20220627_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemuser',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gem_users', to='heroes.herouser', to_field='nft_id'),
        ),
    ]
