# Generated by Django 3.2.13 on 2022-06-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_alter_gemuser_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herouser',
            name='gem_slot5_expire_datetime',
        ),
    ]
