# Generated by Django 4.0.5 on 2022-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_remove_herouser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gem',
            name='is_off_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gem',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
