# Generated by Django 4.0.5 on 2022-07-24 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heroes', '0007_gem_is_off_chain_gem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroOnChain',
            fields=[
                ('nft_id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('base_str', models.IntegerField(db_column='str')),
                ('base_int', models.IntegerField(db_column='int')),
                ('base_vit', models.IntegerField(db_column='vit')),
                ('base_agi', models.IntegerField(db_column='agi')),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_column='isDeleted')),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'indexer_hero_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('expiration_date', models.IntegerField(blank=True, db_column='expirationDate', null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'indexer_item_balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroOffChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.CharField(max_length=255)),
                ('team_slot', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='heroes.hero')),
                ('rank', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_chain_rank', to='heroes.herorank')),
                ('rarity', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heroes_this_rarity', to='heroes.herorarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Individual heroes',
            },
        ),
        migrations.CreateModel(
            name='HeroOffChainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slot', models.IntegerField(db_column='teamSlot')),
                ('exp', models.IntegerField(db_column='exp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hero_off_chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heroes.herooffchain')),
            ],
        ),
        migrations.CreateModel(
            name='HeroOnChainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slot', models.IntegerField(db_column='teamSlot')),
                ('exp', models.IntegerField(db_column='exp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hero_on_chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='heroes.heroonchain')),
            ],
        ),
        migrations.RemoveField(
            model_name='gemuser',
            name='hero',
        ),
        migrations.AddField(
            model_name='gemuser',
            name='hero_nft_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='HeroUser',
        ),
    ]
