# Generated by Django 4.0.5 on 2022-07-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0008_heroonchain_itembalance_herooffchain_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="herooffchain",
            options={"verbose_name_plural": "Off-chain heroes"},
        ),
        migrations.AlterModelOptions(
            name="heroonchain",
            options={"verbose_name_plural": "On-chain heroes"},
        ),
    ]
