# Generated by Django 4.0.5 on 2022-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_alter_herooffchain_options_alter_heroonchain_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.CharField(max_length=255)),
                ('team_slot', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='heroonchaindetail',
            name='hero_on_chain',
        ),
        migrations.AlterModelOptions(
            name='heroonchain',
            options={'managed': False, 'verbose_name_plural': 'On-chain heroes'},
        ),
        migrations.AlterField(
            model_name='herooffchain',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HeroOffChainDetail',
        ),
        migrations.DeleteModel(
            name='HeroOnChainDetail',
        ),
    ]
