# Generated by Django 4.0.5 on 2022-07-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_heroinfo_remove_heroonchaindetail_hero_on_chain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroinfo',
            options={'verbose_name_plural': 'Hero details'},
        ),
    ]
