# Generated by Django 4.0.5 on 2022-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0012_heroinfo_hero_heroinfo_is_on_chain_heroinfo_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroinfo",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
