# Generated by Django 4.0.5 on 2022-07-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0013_heroinfo_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroinfo",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heroes_rank",
                to="heroes.herorank",
                to_field="value",
            ),
        ),
    ]
