# Generated by Django 4.0.5 on 2022-08-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0015_alter_gem_attribute_alter_gemuser_gem_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hero",
            new_name="HeroType",
        ),
    ]
