# Generated by Django 4.0.5 on 2022-08-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0016_rename_hero_herotype"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroUser",
            fields=[
                (
                    "info",
                    models.OneToOneField(
                        blank=True,
                        db_column="id",
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="heroes.heroinfo",
                        to_field="nft_id",
                    ),
                ),
                ("base_str", models.IntegerField(db_column="str")),
                ("base_int", models.IntegerField(db_column="int")),
                ("base_vit", models.IntegerField(db_column="vit")),
                ("base_agi", models.IntegerField(db_column="agi")),
                ("is_deleted", models.BooleanField(db_column="isDeleted")),
                ("created_at", models.DateTimeField(db_column="createdAt")),
                ("updated_at", models.DateTimeField(db_column="updatedAt")),
            ],
            options={
                "verbose_name_plural": "Individual heroes",
                "db_table": "indexer_hero_stats",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="herooffchain",
            name="hero",
        ),
        migrations.RemoveField(
            model_name="herooffchain",
            name="rarity",
        ),
        migrations.RemoveField(
            model_name="herooffchain",
            name="user",
        ),
        migrations.DeleteModel(
            name="HeroOnChain",
        ),
        migrations.AlterModelOptions(
            name="herotype",
            options={"verbose_name_plural": "Hero's types"},
        ),
        migrations.DeleteModel(
            name="HeroOffChain",
        ),
    ]
