# Generated by Django 4.0.5 on 2022-08-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0018_alter_gem_attribute_alter_gemuser_gem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gem",
            name="is_off_chain",
        ),
        migrations.AddField(
            model_name="gem",
            name="is_on_chain",
            field=models.BooleanField(default=True),
        ),
    ]
