# Generated by Django 4.0.5 on 2022-08-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_alter_heroinfo_options_remove_heroinfo_is_on_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='team_slot',
        ),
    ]
