# Generated by Django 4.0.5 on 2022-08-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heroes', '0021_remove_heroinfo_team_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='gem_slot',
            field=models.JSONField(default=heroes.models.default_gem_slot_dict),
        ),
        migrations.AlterField(
            model_name='gem',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='heroes.gemattribute'),
        ),
        migrations.AlterField(
            model_name='gemuser',
            name='gem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='heroes.gem'),
        ),
        migrations.AlterField(
            model_name='gemuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to=settings.AUTH_USER_MODEL),
        ),
    ]
