# Generated by Django 4.0.5 on 2022-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0023_rename_hero_heroinfo_hero_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gem',
            name='id',
        ),
        migrations.AlterField(
            model_name='gem',
            name='nft_id',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
