# Generated by Django 4.0.5 on 2022-09-13 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0024_remove_gem_id_alter_gem_nft_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemuser',
            name='gem_slot',
        ),
        migrations.RemoveField(
            model_name='gemuser',
            name='hero_nft_id',
        ),
        migrations.RemoveField(
            model_name='gemuser',
            name='user',
        ),
        migrations.AddField(
            model_name='gemuser',
            name='hero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.herouser'),
        ),
        migrations.AddField(
            model_name='gemuser',
            name='slot',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='gemuser',
            name='gem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.gem'),
        ),
    ]
