# Generated by Django 4.0.5 on 2022-09-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0026_gemuser_hero_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemuser',
            name='gem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.gem'),
        ),
    ]
