# Generated by Django 4.0.5 on 2022-09-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0027_alter_gemuser_gem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemuser',
            name='hero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.heroinfo'),
        ),
    ]
