# Generated by Django 4.0.5 on 2022-09-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0028_alter_gemuser_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemuser',
            name='gem',
        ),
        migrations.RemoveField(
            model_name='gemuser',
            name='hero',
        ),
        migrations.AddField(
            model_name='gemuser',
            name='gem_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.gem'),
        ),
        migrations.AddField(
            model_name='gemuser',
            name='hero_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.heroinfo'),
        ),
    ]
