# Generated by Django 4.0.5 on 2022-09-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0029_remove_gemuser_gem_remove_gemuser_hero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gemuser',
            old_name='gem_id',
            new_name='gem',
        ),
        migrations.RenameField(
            model_name='gemuser',
            old_name='hero_id',
            new_name='hero',
        ),
    ]
