# Generated by Django 4.0.5 on 2022-09-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0030_rename_gem_id_gemuser_gem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='gem_slot',
        ),
    ]
