# Generated by Django 4.0.5 on 2022-09-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0031_remove_heroinfo_gem_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBalance',
        ),
    ]
