# Generated by Django 3.2.13 on 2022-06-15 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamina_last_updated_value', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('stamina_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin_pending', models.FloatField(default=0)),
                ('coin_last_withdrawn', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_banned', models.BooleanField(default=False)),
                ('hero_slot5_expired', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stage_current', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='stages.stage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
