# Generated by Django 3.2.13 on 2022-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stamina_last_updated_value',
            field=models.DecimalField(decimal_places=5, default=100.0, max_digits=15),
        ),
    ]
