# Generated by Django 3.2.13 on 2022-06-27 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_stamina_last_updated_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gem_slot5_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
