# Generated by Django 3.2.13 on 2022-06-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_gem_slot5_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gem_slot5_lv',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='hero_slot5_lv',
            field=models.IntegerField(default=1),
        ),
    ]
