# Generated by Django 3.2.13 on 2022-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20220627_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gem_slot5_lv',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hero_slot5_lv',
        ),
        migrations.AddField(
            model_name='player',
            name='gem_slot5_max_lv',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='player',
            name='hero_slot5_max_lv',
            field=models.IntegerField(default=20),
        ),
    ]
