# Generated by Django 4.0.5 on 2022-08-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_player_gold"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
