# Generated by Django 4.0.5 on 2022-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_player_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="team_slot",
            field=models.JSONField(
                default={
                    "slot1": None,
                    "slot2": None,
                    "slot3": None,
                    "slot4": None,
                    "slot5": None,
                }
            ),
        ),
    ]
