# Generated by Django 4.0.5 on 2022-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_team_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='address',
        ),
        migrations.AddField(
            model_name='player',
            name='is_newcomer',
            field=models.BooleanField(default=True),
        ),
    ]
