# Generated by Django 4.0.5 on 2022-09-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_remove_player_address_player_is_newcomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gem_slot5_expired',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gem_slot5_max_lv',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hero_slot5_expired',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hero_slot5_max_lv',
        ),
    ]
