# Generated by Django 4.0.5 on 2022-09-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_remove_player_gem_slot5_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stage_current',
        ),
    ]
