# Generated by Django 4.0.5 on 2022-09-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_remove_player_stage_current'),
        ('stages', '0002_stage_level_required_phase_gameplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_play',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_game_play', to='stages.gameplay'),
        ),
    ]
