# Generated by Django 4.0.5 on 2022-09-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_player_game_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_play',
        ),
    ]
