# Generated by Django 4.0.5 on 2022-09-21 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_gameplaystage_remove_gameplay_player_and_more'),
        ('players', '0014_remove_player_game_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_play_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_game_play_stage', to='stages.gameplaystage'),
        ),
    ]
