# Generated by Django 4.0.5 on 2022-12-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_player_game_play_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coin_earned',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AlterField(
            model_name='player',
            name='coin_pending',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'COMPLETED'), (3, 'FAILED')], default=1)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('nounce', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tx_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transaction', to='players.player')),
            ],
        ),
    ]
