# Generated by Django 4.0.5 on 2023-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player_coin_earned_alter_player_coin_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coin_processing',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
    ]
